services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: robotdreams
      POSTGRES_PASSWORD: robotdreams
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

#  eureka-server:
#    image: eureka-server:0.0.1-SNAPSHOT
#    hostname: eureka-server
#    ports:
#      - "8761:8761"
#
#  schoolmanage:
#    image: schoolmanage-service:0.0.1-SNAPSHOT
#    depends_on:
#      - postgres
#      - eureka-server
#    environment:
#      - "SPRING_PROFILES_ACTIVE=docker"
#    ports:
#      - '8080:8080'
#    networks:
#      - postgres
#    links:
#      - eureka-server
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin: